import pandas as pd
import numpy as np

def create_features(df):
    """
    Given a dataframe with date, store_nbr, family, and sales,
    creates time-series features.
    """
    print("Creating date features...")
    df['day_of_week'] = df['date'].dt.dayofweek
    df['month'] = df['date'].dt.month
    df['year'] = df['date'].dt.year
    df['is_weekend'] = df['day_of_week'].apply(lambda x: 1 if x >= 5 else 0)
    
    print("Loading and processing holidays...")
    df_holidays = pd.read_csv('holidays_events.csv')
    df_holidays['date'] = pd.to_datetime(df_holidays['date'])
    # Filter out transferred holidays logically
    df_holidays = df_holidays[df_holidays['transferred'] == False]
    
    national_holidays = df_holidays[df_holidays['locale'] == 'National']['date'].unique()
    all_holidays = df_holidays['date'].unique()
    
    df['is_holiday'] = df['date'].isin(all_holidays).astype(int)
    df['is_national_holiday'] = df['date'].isin(national_holidays).astype(int)
    
    print("Creating lag & rolling features. This might take a moment...")
    
    # We must group by store and family to create accurate lags
    # Using shift() directly on the grouped object
    grouped = df.groupby(['store_nbr', 'family'])['sales']
    
    # Lags: 1 day, 7 days
    df['sales_lag_1'] = grouped.shift(1)
    df['sales_lag_7'] = grouped.shift(7)
    
    # Rolling averages: 7 days and 30 days
    # Since the data is daily and sorted, rolling on shift(1) avoids data leakage!
    df['rolling_mean_7'] = grouped.shift(1).rolling(window=7, min_periods=1).mean().reset_index(0, drop=True)
    df['rolling_mean_30'] = grouped.shift(1).rolling(window=30, min_periods=1).mean().reset_index(0, drop=True)
    
    # Drop NaNs that were produced by the lags
    print("Dropping NA values generated by lagging...")
    df = df.dropna()
    
    # Encode categorical features
    # type, city, state, cluster (from stores.csv), family (from train.csv)
    cat_columns = ['family', 'city', 'state', 'type']
    
    # Convert to category types for XGBoost to handle (or use one-hot, but LightGBM/XGBoost handles category format well if specified or we can just use simple label encoding for robust compatibility)
    from sklearn.preprocessing import LabelEncoder
    label_encoders = {}
    for col in cat_columns:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
        label_encoders[col] = le
        
    print("Feature engineering complete!")
    return df, label_encoders

if __name__ == "__main__":
    from data_preparation import load_and_merge_data
    df = load_and_merge_data(start_date='2017-07-01') # Very short period for quick test
    df_feat, encoders = create_features(df)
    print("Features shape:", df_feat.shape)
    print("Columns:", df_feat.columns.tolist())
